//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vendimia
{
    using System;
    using System.Collections.Generic;
    
    public partial class Configuracion
    {
        public double TasaFinanciamiento { get; set; }
        public double Enganche { get; set; }
        public int PlazoMaximo { get; set; }
    }
}
