//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vendimia
{
    using System;
    using System.Collections.Generic;
    
    public partial class Venta
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Venta()
        {
            this.VentaDetalle = new HashSet<VentaDetalle>();
        }
    
        public int Id_Venta { get; set; }
        public Nullable<int> Cliente_Id { get; set; }
        public Nullable<decimal> Importe { get; set; }
        public Nullable<double> TasaFinanciamiento { get; set; }
        public Nullable<int> Plazo { get; set; }
        public Nullable<double> Enganche { get; set; }
        public Nullable<decimal> MontoEnganche { get; set; }
        public Nullable<decimal> MontoBonificacion { get; set; }
        public Nullable<decimal> Mensualidad { get; set; }
        public Nullable<decimal> Total { get; set; }
        public int Estatus_Id { get; set; }
        public System.DateTime FechaCreacion { get; set; }
    
        public virtual Cliente Cliente { get; set; }
        public virtual Estatus Estatus { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<VentaDetalle> VentaDetalle { get; set; }
    }
}
