//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vendimia
{
    using System;
    using System.Collections.Generic;
    
    public partial class VentaDetalle
    {
        public int Id_VentaDetalle { get; set; }
        public int Venta_Id { get; set; }
        public int Articulo_Id { get; set; }
        public double Cantidad { get; set; }
    
        public virtual Articulo Articulo { get; set; }
        public virtual Venta Venta { get; set; }
    }
}
